### ISSUE TITLE
Doesn't recognize FILE data type, need to preprocessed a step further.

### ISSUE THREAD

**Issue by tassosblackg** [tassosblackg/thePyrCer#3]
While parsing `FILE` datatypes raises ERROR:

> python3 pyrCer.py a11f5.c
> Traceback (most recent call last):
>   File "./pyrCer.py", line 211, in <module>
>     ast = pyc.parse_file(
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/__init__.py",
> line 90, in parse_file
>     return parser.parse(text, filename)
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/c_parser.py",
> line 149, in parse
>     return self.cparser.parse(
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py",
> line 331, in parse
>     return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py",
> line 1199, in parseopt_notrack
>     tok = call_errorfunc(self.errorfunc, errtoken, self)
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/ply/yacc.py",
> line 193, in call_errorfunc
>     r = errorfunc(token)
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/c_parser.py",
> line 1858, in p_error
>     self._parse_error(
>   File
> "/home/alexandros/.local/lib/python3.8/site-packages/pycparser/plyparser.py",
> line 67, in _parse_error
>     raise ParseError("%s: %s" % (coord, msg))
> pycparser.plyparser.ParseError: C_code_inputs/a11f5_after.c:23:45:
> before: FILE

After editing parser arguments to use `fake_headers` the problem continues to rise 

```
ast = parse_file(
        filename,
        use_cpp=True,
        cpp_path="gcc",
        cpp_args=[
            "-std=c99",
            "-nostdinc",
            "-E",
      
            r"-Iutils/fake_libc_include",
        ],
    )
```
And I got an error like this :

> File "/home/tassosblackg/Projects/pars.py", line 11, in
> ast = parse_file(
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/init.py", line 90, in parse_file
> return parser.parse(text, filename)
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/c_parser.py", line 149, in parse
> return self.cparser.parse(
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 331, in parse
> return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
> tok = call_errorfunc(self.errorfunc, errtoken, self)
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
> r = errorfunc(token)
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/c_parser.py", line 1858, in p_error
> self._parse_error(
> File "/home/tassosblackg/hellpy/lib/python3.9/site-packages/pycparser/plyparser.py", line 67, in _parse_error
> raise ParseError("%s: %s" % (coord, msg))
> pycparser.plyparser.ParseError: utils/fake_libc_include/_fake_typedefs.h:175:24: before: atomic_bool

I've tried to add an extra cpp_arg with

`"-D atomic_bool(x)=",`

**Comment by tassosblackg** [comment]
See post : https://github.com/eliben/pycparser/issues/427
